"""
Django settings for jahanpars project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# Take environment variables from .env file
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-cg74tv!!7ixcgjh!m(&)(w(a&qp-#c%c00ni3m-rv(r@kw3eq@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # کتابخانه Django REST Framework
    'rest_framework',
    # احراز هویت توکن‌های JWT
    'rest_framework_simplejwt',
    # پشتیبانی از CORS
    'corsheaders',
    # تقویم و تاریخ شمسی
    'django_jalali',
    # اپلیکیشن اصلی سیستم بالانس متریال
    'balance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # فشرده‌سازی پاسخ‌ها برای حداکثر سرعت در انتقال حجم دیتای بالا
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # میدل‌ویر CORS (باید قبل از CommonMiddleware باشد)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jahanpars.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jahanpars.wsgi.application'
ASGI_APPLICATION = 'jahanpars.asgi.application'

# ─── Caching (Redis) ────────────────────────────────────────────────────────
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # استفاده از تنظیمات محیطی PostgreSQL (یا پیش‌فرض SQLite) با اتصال پایدار برای سرعت بالا
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}

# فعال‌سازی Connection Pooling برای دیتابیس (پستگرس و غیره) جهت جلوگیری از قطع و وصل شدن مکرر
if DATABASES['default']['ENGINE'] != 'django.db.backends.sqlite3':
    DATABASES['default']['CONN_MAX_AGE'] = 600  # باز نگه داشتن اتصال برای ۱۰ دقیقه

# ─── بهینه‌سازی دیتابیس برای حداکثر سرعت ─────────────────────────────────────
if 'sqlite' in DATABASES['default']['ENGINE']:
    DATABASES['default']['OPTIONS'] = {
        'timeout': 20,
        'pragmas': {
            'journal_mode': 'wal',          # Write-Ahead Logging (شدیدا سرعت می‌بخشد)
            'synchronous': 'NORMAL',        # در حالت wal امن و سریع است
            'cache_size': -64000,           # 64MB Cache
            'temp_store': 'MEMORY',         # ذخیره tempها در رم
            'mmap_size': 268435456,         # 256MB Mmap
        }
    }

# ─── محافظت پروداکشن: جلوگیری از اجرا با SQLite ──────────────────────────
if not DEBUG and 'sqlite' in DATABASES['default']['ENGINE']:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'SQLite is not supported in production. '
        'Please set DATABASE_URL to a PostgreSQL connection string.'
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ─── مدل کاربر سفارشی ────────────────────────────────────────────────────────
# به Django می‌گوییم از مدل User سفارشی ما (با فیلد role) استفاده کند
AUTH_USER_MODEL = 'balance.User'

# ─── تنظیمات Django REST Framework ──────────────────────────────────────────
REST_FRAMEWORK = {
    # احراز هویت هم از طریق توکن JWT و هم Session (برای مرورگر/پنل ادمین)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # پیش‌فرض: کاربر باید احراز هویت شده باشد
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # فرمت تاریخ استاندارد ISO
    'DATE_FORMAT': '%Y-%m-%d',
    'DATE_INPUT_FORMATS': ['%Y-%m-%d'],
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S',
    # محدودیت حداکثر اندازه درخواست (10 مگابایت)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '200/minute',
        'download': '1000/hour',
    },
}

# ─── تنظیمات امنیتی (فعال در محیط Production) ────────────────────────────────
# این تنظیمات فقط روی سرور واقعی (DEBUG=False) فعال می‌شوند
if not DEBUG:
    # الزامی‌کردن HTTPS برای Cookie‌های Session و CSRF
    SESSION_COOKIE_SECURE   = True
    CSRF_COOKIE_SECURE      = True
    # جلوگیری از نمایش سایت در iframe (کلیک جعلی)
    X_FRAME_OPTIONS         = 'DENY'
    # HSTS: به مرورگر می‌گوید همیشه HTTPS استفاده کند (۱ سال)
    SECURE_HSTS_SECONDS     = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # ریدایرکت HTTP به HTTPS
    SECURE_SSL_REDIRECT     = True

# ─── تنظیمات Session ─────────────────────────────────────────────────────────
# نشست کاربر بعد از ۸ ساعت بی‌فعالیت منقضی می‌شود
SESSION_COOKIE_AGE = 8 * 60 * 60  # 8 ساعت به ثانیه
SESSION_SAVE_EVERY_REQUEST = True   # تجدید زمان session با هر درخواست


# ─── تنظیمات CORS ────────────────────────────────────────────────────────────
# در محیط توسعه (برای اتصال به React SPA)
CORS_ALLOW_ALL_ORIGINS = True
# اگر نیاز به احراز هویت با کوکی‌های سشن برای فرانت‌اند بود:
# CORS_ALLOW_CREDENTIALS = True 


# ─── Celery Configuration ───────────────────────────────────────────────────
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tehran'


# ─── Channels Configuration ─────────────────────────────────────────────────
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [env('REDIS_URL', default='redis://127.0.0.1:6379/2')],
        },
    },
}


# ─── MinIO / S3 Object Storage (اختیاری) ────────────────────────────────────
# اگر هر ۴ متغیر محیطی تنظیم شده باشد، فایل‌های خروجی روی MinIO/S3 ذخیره می‌شوند.
# در غیر این صورت، از MEDIA_ROOT محلی استفاده خواهد شد.
MINIO_ENDPOINT = env('MINIO_ENDPOINT', default='')
MINIO_ACCESS_KEY = env('MINIO_ACCESS_KEY', default='')
MINIO_SECRET_KEY = env('MINIO_SECRET_KEY', default='')
MINIO_BUCKET = env('MINIO_BUCKET', default='jahanpars-exports')

EXPORT_STORAGE = None  # پیش‌فرض: دیسک محلی
if MINIO_ENDPOINT and MINIO_ACCESS_KEY and MINIO_SECRET_KEY and MINIO_BUCKET:
    from jahanpars.storage import AutoCreateS3Storage
    EXPORT_STORAGE = AutoCreateS3Storage(
        access_key=MINIO_ACCESS_KEY,
        secret_key=MINIO_SECRET_KEY,
        bucket_name=MINIO_BUCKET,
        endpoint_url=MINIO_ENDPOINT,
        querystring_auth=True,
        querystring_expire=3600,
        default_acl=None,
        file_overwrite=True,
    )
